# Generated by Django 3.2.4 on 2021-06-26 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('url_clean', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_pieza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('url_clean', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('url_clean', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('url_clean', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('volumen', models.TextField()),
                ('ancho', models.TextField()),
                ('hora_estimada', models.TextField()),
                ('hora_real', models.TextField()),
                ('precio_costo', models.TextField()),
                ('precio_venta', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listelement.categoria')),
                ('estado_pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listelement.estado_pieza')),
                ('tipo_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listelement.tipo_material')),
            ],
        ),
    ]
